#############################################################
#                                                           #
# Copyright (c) 2021, University of California, Los Angeles #
#                                                           #
# Authors: Kenny J. Chen, Brett T. Lopez                    #
# Contact: kennyjchen@ucla.edu, btlopez@ucla.edu            #
#                                                           #
#############################################################

dlo:

  odomNode:

    initialPose:
      use: false  #false: 在初始化阶段(机器静止状态)计算imu的roll, pitch
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0

    preprocessing:
      cropBoxFilter:
        use: true
        size: 1.0
      voxelFilter:
        scan:
          use: true #每帧scan是否进行降采样
          res: 0.25 #每帧scan降采样分辨率
        submap:
          use: true #每帧scan在作为keyframe时，是否继续进一步降采样
          res: 0.5

    keyframe:
      threshD: 5.0
      threshR: 45.0

    submap:
      keyframe:
        knn: 10  #10帧keyframes构成local map
        kcv: 10
        kcc: 10

    imu:
      calibTime: 3   #最开始imu得静止这么长时间计算bias初值(累加平均)
      bufferSize: 2000

    gicp:
      minNumPoints: 10
      s2s:
        kCorrespondences: 10
        maxCorrespondenceDistance: 1.0
        maxIterations: 32
        transformationEpsilon: 0.01
        euclideanFitnessEpsilon: 0.01
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
      s2m:
        kCorrespondences: 20
        maxCorrespondenceDistance: 0.5
        maxIterations: 32
        transformationEpsilon: 0.01
        euclideanFitnessEpsilon: 0.01
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
